version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/j7z6d3z4
      - docker build -t public.ecr.aws/j7z6d3z4/my-react-app:latest .
      - docker push public.ecr.aws/j7z6d3z4/my-react-app:latest

artifacts:
  files:
    - '**/*'
  discard-paths: yes

