version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.20.2
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Build completed successfully
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - docker build -t my-react-app .
      - docker tag my-react-app:latest public.ecr.aws/j7z6d3z4/my-react-app:latest
      - docker push public.ecr.aws/j7z6d3z4/my-react-app:latest
      - echo Docker image pushed successfully

artifacts:
  files:
    - '**/*'


