version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - docker build -t public.ecr.aws/j7z6d3z4/my-react-app:latest .
      - docker push public.ecr.aws/j7z6d3z4/my-react-app:latest
